[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mach = { path = "../mach" }
otlp = { path = "../otlp" }
num = "0.4.0"
tonic = { version = "0.6.2", features = ["prost", "compression", "transport"] }
tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = "0.1.8"
prost = "0.9"
futures = { version = "0.3.21", features = ["executor"] }
rand = "0.8.4"
seq-macro = "0.3.0"
dashmap = "4.0.2"
lazy_static = "1.4"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
rtrb = "0.2.0"
random-string = "1.0.0"
regex = "1.5.5"
clap = { version = "3.1.12", features = ["derive"] }
rdkafka = "0.28.0"
bincode = "1.3.3"
zstd = "0.11.1"
timer = "0.2.0"
chrono = "0.4.19"
roaring = "0.9.0"
tower = { version = "0.4" }
redis = "0.21.5"
fxhash = "0.2.1"

[[bin]]
name = "tsdb"
path = "src/tsdb.rs"

[[bin]]
name = "tsdb-client"
path = "src/tsdb_client.rs"

[[bin]]
name = "file2mach"
path = "src/file_to_mach.rs"

[[bin]]
name = "data-latency-bench"
path = "src/data_latency_bench.rs"

[[bin]]
name = "otlp-server"
path = "src/otlp_server2.rs"

[[bin]]
name = "mach-server"
path = "src/mach-server.rs"

[[bin]]
name = "otlp-consumer"
path = "src/otlp-consumer.rs"

[[bin]]
name = "load-data"
path = "src/load_data.rs"

[[bin]]
name = "parse-traces"
path = "src/parse_traces.rs"

[[bin]]
name = "otlp-load"
path = "src/otlp_load_bench.rs"


[[bin]]
name = "simple_bench"
path = "src/simple_bench.rs"

[profile.release]
debug = true
#[[bin]]
#name = "writer-client"
#path = "src/writer_client.rs"

#[[bin]]
#name = "reader-client"
#path = "src/reader_client.rs"

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["prost", "compression"] }
