[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mach = { path = "../mach" }
tonic = { version = "0.6.2", features = ["prost", "compression"] }
tokio = "1.17.0"
tokio-stream = "0.1.8"
prost = "0.9"
futures = "0.3.21"
rand = "0.8.4"
lazy_static = "1.4"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
rtrb = "0.2.0"

[[bin]]
name = "tsdb"
path = "src/tsdb.rs"

[[bin]]
name = "tsdb-client"
path = "src/tsdb_client.rs"

[[bin]]
name = "writer-client"
path = "src/writer_client.rs"

[[bin]]
name = "microbench-logs"
path = "src/bench/microbench_logs.rs"

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["prost", "compression"] }
