[package]
name = "mach-private"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0.2"
seq-macro = "0.2"
num = "0.4.0"
bitpacking = "0.8.4"
lz4_flex = "0.8.2"
async-std = { version = "1.9", features = ["unstable", "attributes"] }
libc = "0.2.96"

[dev-dependencies]
tempdir = "0.3"
rand = "0.8.4"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
lazy_static = "1.4"

